### PR TITLE
Path and Line Detection

### PR DESCRIPTION
**Pull request by VanAchte**
Path Detection Code needs some work done to reduce the amount of false positives found on the image for both sides of the path we are on. Line Detection uses thresholding and Hough transform to find the line, could use the contours method which has been implemented on my personal repository. Part of the code in line detection is commented out. That code uses hough transforms to find the line, the current version uses the contours method.

### CODE REVIEW

**Comment by ptressel** [comment]
Aha!  All the extraneous commits are gone -- good job, Conor!  Several questions:

Should this go in the main repo instead?

This should go in a subdirectory, but where to put it depends on which repo it's in, so we should answer the above question first.

Can you add a note to the documentation comment in the .h file that tells how to compile and run this, and what the input should be?

Is the commented out code from a previous version of this file?  If this is your first checked in version, and the commented out stuff is just old material you don't want to keep, then it can be removed.  If there was a prior version, then it would be good to check that in first, and then your new version.  That makes a record of the old version, so you can refer to it if you need.  And it makes it easy to see the changes, as they will show up in a git diff.  (Note you can have more than one commit in a pull request, so you don't need to do two pull requests.)

**Comment by VanAchte** [comment]
This should go in a subdirectory for sure, perhaps we create a new subfolder for C7? I don't have a .h file for  the code but can make one, should I do that or would including a README work as well? The commented out code is from a prior version which can be still used depending on how someone wants to use it.  I can check in a prior version and then the next version so we have two different copies.

**Comment by ptressel** [comment]
Let's figure out which repo it's for.  What will this run on?  Is it for a RasPi?  Assuming so because of CV.  I won't be able to look at it more today -- I have another obligation -- but maybe we can get this into the right place on Thursday.

**Comment by ptressel** [comment]
I should also mention that you can update this PR just by pushing a new version of the same branch.  It's ok to have changes in separate commits for now, and at the end, tidy everything up by "squashing" the commits.

**Pull request merged**
